test_that("audit and diagnostics preserve estimates and grid order", {
  set.seed(2026)
  x <- runif(100); y <- 1+2*x^2+rnorm(100)
  z <- c(.8,.2,.5,.2)
  a <- llqr_seq_ppro(x,y,z=z,h=.3,kernel="epanechnikov")
  b <- llqr_seq_ppro(x,y,z=z,h=.3,kernel="epanechnikov",audit=TRUE,diagnostics=TRUE)
  expect_identical(names(a),c("ll_est","d_ll_est","z","h"))
  expect_identical(a$ll_est,b$ll_est)
  expect_identical(a$d_ll_est,b$d_ll_est)
  expect_identical(b$z,z)
  expect_identical(b$diagnostics$H_seq[2,],b$diagnostics$H_seq[4,])
  expect_false(attr(a,"solver_info")$fallback_triggered)
  expect_identical(attr(a,"solver_info")$returned_backend,"unified_u11")
  expect_true(attr(b,"solver_info")$audit)
  expect_error(llqr_seq_ppro(x,y,audit=NA),"TRUE or FALSE")
  expect_error(llqr_seq_ppro(x,y,diagnostics=1),"TRUE or FALSE")
})
test_that("TVCQR full audit is optional and leaves the estimator unchanged", {
  set.seed(2027); x<-matrix(rnorm(300),100,3);y<-rnorm(100)
  a<-tvcqr_seq_ppro(x,y);b<-tvcqr_seq_ppro(x,y,audit=TRUE,diagnostics=TRUE)
  expect_identical(a$theta_ll_est,b$theta_ll_est)
  expect_identical(a$beta_full_est,b$beta_full_est)
  expect_identical(dim(b$diagnostics$H_seq),c(100L,8L))
  expect_identical(dim(b$diagnostics$path),c(100L,18L))
})
test_that("zero-weight basis padding cannot hide deficient positive support", {
  x<-c(seq(0,.5,length.out=30),rep(1,20));y<-sin(x)+seq_along(x)/100
  expect_error(llqr_seq_ppro(x,y,z=c(.2,1),h=.1,kernel="epanechnikov"),"rank deficient")
})
